### ISSUE TITLE
Unable to run dogtail test scripts of xreader (Cinnamon crash)

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xreader#15]
What I did:
1) enabled AT with `gsettings set org.gnome.desktop.interface toolkit-accessibility true`
2) cd xreader/test/
3) ./test1.py

Running the scripts in folder `test` crashes cinnamon with the following console output:

```
/usr/lib/python2.7/dist-packages/gi/types.py:259: RuntimeWarning: Mixin class dogtail.tree.Application is an old style class, please update this to derive from "object".
  RuntimeWarning)
/usr/lib/python2.7/dist-packages/gi/types.py:259: RuntimeWarning: Mixin class dogtail.tree.Node is an old style class, please update this to derive from "object".
  RuntimeWarning)
/usr/lib/python2.7/dist-packages/gi/types.py:259: RuntimeWarning: Mixin class dogtail.tree.Root is an old style class, please update this to derive from "object".
  RuntimeWarning)

(xreader:7934): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(xreader:7934): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

** (test1.py:7928): WARNING **: Unable to open bus connection: Failed to connect to socket /run/user/1000/at-spi2-TUXLJY/socket: Connection refused

** (test1.py:7928): WARNING **: Unable to open bus connection: Failed to connect to socket /run/user/1000/at-spi2-77KJJY/socket: Connection refused

** (test1.py:7928): WARNING **: AT-SPI: Error in GetItems, sender=org.freedesktop.DBus, error=The name :1.47 was not provided by any .service files

** (test1.py:7928): WARNING **: AT-SPI: Error in GetItems, sender=org.freedesktop.DBus, error=The name :1.46 was not provided by any .service files
Creating logfile at /tmp/dogtail-pemoser/logs/test1_20160620-142817_debug ...
Traceback (most recent call last):
  File "/home/pemoser/projects/xreader/test/test1.py", line 10, in <module>
    run('xreader')
  File "/usr/lib/python2.7/dist-packages/dogtail/procedural.py", line 371, in run
    focus.application(application)
  File "/usr/lib/python2.7/dist-packages/dogtail/procedural.py", line 66, in __call__
    app = self.desktop.findChild(pred, recursive = False, retry = False)
  File "/usr/lib/python2.7/dist-packages/dogtail/tree.py", line 793, in findChild
    result = self._fastFindChild(pred.satisfiedByNode, recursive)
  File "/usr/lib/python2.7/dist-packages/dogtail/tree.py", line 760, in _fastFindChild
    if pred(child): return child
  File "/usr/lib/python2.7/dist-packages/dogtail/predicate.py", line 98, in satisfiedByNode
    return node.roleName=='application' and stringMatches(self.appName, node.name)
GError: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Exception ImportError: 'No module named os' in <bound method Lock.__del__ of <dogtail.utils.Lock object at 0x7f8fc0ce8e90>> ignored
Exception ImportError: 'No module named os' in <bound method Lock.__del__ of <dogtail.utils.Lock object at 0x7f8fc0ce8d10>> ignored

```

`cat  /tmp/dogtail-pemoser/logs/test1_20160620-142817_debug` gives:

```
##### test1_20160620-142817_debug
Traceback (most recent call last):
  File "/home/pemoser/projects/xreader/test/test1.py", line 10, in <module>
    run('xreader')
  File "/usr/lib/python2.7/dist-packages/dogtail/procedural.py", line 371, in run
    focus.application(application)
  File "/usr/lib/python2.7/dist-packages/dogtail/procedural.py", line 66, in __call__
    app = self.desktop.findChild(pred, recursive = False, retry = False)
  File "/usr/lib/python2.7/dist-packages/dogtail/tree.py", line 793, in findChild
    result = self._fastFindChild(pred.satisfiedByNode, recursive)
  File "/usr/lib/python2.7/dist-packages/dogtail/tree.py", line 760, in _fastFindChild
    if pred(child): return child
  File "/usr/lib/python2.7/dist-packages/dogtail/predicate.py", line 98, in satisfiedByNode
    return node.roleName=='application' and stringMatches(self.appName, node.name)
GError: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by Piiit** [comment]
Maybe I did not configure the system right, but anyway it should not crash cinnamon...

**Comment by Piiit** [comment]
Please note: It does not crash when AT is enabled for cinnamon with `gsettings set org.cinnamon.desktop.interface toolkit-accessibility true`

**Comment by icarter09** [comment]
@Piiit is still an issue?

**Comment by icarter09** [comment]
@Piiit I believe this ticket is no longer relevant due to the changes that have been done to the tests. I'll close this ticket, but please reopen if you experience issues.
