### ISSUE TITLE
Crash in libpdfdocument when opening specific pdf document

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/xreader#227]
```
 * Xreader version - 1.8.1
 * Distribution - Alt Linux Sisyphus
```

**Issue**
When opening specific pdf document 

https://drive.google.com/file/d/1UQ6R7RmazWYPnnwsV0grS3mFqAgDie60

xreader crashes with follow backtrace
```
(gdb) bt
#0  build_tree (pdf_document=pdf_document@entry=0xd01f20, model=model@entry=0x10d1050, parent=parent@entry=0x0, iter=iter@entry=0x8c1280) at ev-poppler.cc:1212
#1  0x00007fff63dfa9c4 in pdf_document_links_get_links_model (document_links=<optimized out>) at ev-poppler.cc:1261
#2  0x00007ffff754ea0a in ev_job_links_run (job=0x1111770) at ev-jobs.c:385
#3  0x00007ffff75505e2 in ev_job_thread (job=0x1111770) at ev-job-scheduler.c:184
#4  ev_job_thread_proxy (data=<optimized out>) at ev-job-scheduler.c:217
#5  0x00007ffff5499c65 in g_thread_proxy (data=0x110e0f0) at gthread.c:784
#6  0x00007ffff4e7932a in start_thread (arg=0x7fff7884c700) at pthread_create.c:463
#7  0x00007ffff4babfaf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) l 1212
1207	
1208			if (!action)
1209				continue;
1210	
1211			/* Block zoom change when action link is pressed (bug fix #175) */
1212			action->goto_dest.dest->change_zoom = 0;
1213	
1214			link = ev_link_from_action (pdf_document, action);
1215			if (!link || strlen (ev_link_get_title (link)) <= 0) {
1216				poppler_action_free (action);
(gdb) p action->goto_dest
$3 = {type = POPPLER_ACTION_NONE, title = 0x7fff680cc8c0 "用户手册标准图框", dest = 0x0}
```

**Steps to reproduce**
1. Download document from https://drive.google.com/file/d/1UQ6R7RmazWYPnnwsV0grS3mFqAgDie60
2. Open it with xreader

**Expected behaviour**
Working document

**Other information**
None

**Comment by mickaelalbertus** [comment]
Thanks for reporting this bug! It's corrected now :)

**Comment by Piiit** [comment]
@vladimir-didenko Is it solved?

**Comment by vladimir-didenko** [comment]
> @vladimir-didenko Is it solved?

Yes it is. I am closing this issue.
