### ISSUE TITLE
Xreader segfaults if `.epub` filename contains hash `#`

### ISSUE THREAD

**Issue by dejj** [linuxmint/xreader#485]
```
 * Xreader version: 2.8.3
 * Distribution: Mint 20.1
```

**Issue**

Xreader crashes on some `.epub` files if the filename contains an octothorpe / hash `#`.
If the `#` is removed, then Xreader can open the file.

**Steps to reproduce**

Have an `.epub` file.
Insert `#` into filename.
Open `xreader file\ #tag.epub`.
Xreader opens briefly, then closes.

**Expected behaviour**

Epub backend should not segfault.

**Other information**
gdb stacktrace:
```gdb
#0  0x00007fffe656c3d3 in page_set_function (Link=0x7fff840097a0, contentList=0x5555557d4840 = {...}) at ../../backend/epub/epub-document.c:1634
#1  0x00007ffff7bdfd50 in g_list_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fffe656c4bc in epub_document_set_index_pages (index=0x5555557d4ca0 = {...}, contentList=0x5555557d4840 = {...}) at ../../backend/epub/epub-document.c:1653
#3  0x00007fffe656c9cd in epub_document_load (document=0x555555c00490, uri=0x555555aa2400 "file:///home/dejj/Dokumente/ebook%20%23food/@SabrinaGhayour%202019%20%23food.epub", error=0x7fff936d19a0) at ../../backend/epub/epub-document.c:1779
#4  0x00007ffff7f34554 in ev_document_load (document=0x555555c00490, uri=0x555555aa2400 "file:///home/dejj/Dokumente/ebook%20%23food/@SabrinaGhayour%202019%20%23food.epub", error=0x7fff936d1a30) at ../../libdocument/ev-document.c:249
#5  0x00007ffff7f37423 in ev_document_factory_get_document (uri=0x555555aa2400 "file:///home/dejj/Dokumente/ebook%20%23food/@SabrinaGhayour%202019%20%23food.epub", error=0x7fff936d1a80) at ../../libdocument/ev-document-factory.c:237
#6  0x00007ffff7f86e01 in ev_job_load_run (job=0x555555b920f0) at ../../libview/ev-jobs.c:1124
#7  0x00007ffff7f84c05 in ev_job_run (job=0x555555b920f0) at ../../libview/ev-jobs.c:219
#8  0x00007ffff7f886e2 in ev_job_thread (job=0x555555b920f0) at ../../libview/ev-job-scheduler.c:184
#9  0x00007ffff7f887c7 in ev_job_thread_proxy (data=0x0) at ../../libview/ev-job-scheduler.c:217
#10 0x00007ffff7c0dad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff35d5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007ffff6d56293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by dejj** [comment]
Created PR https://github.com/linuxmint/xreader/pull/486

**Comment by dejj** [comment]
The PR only fixes the crash at startup. There is still an issue with finding embedded images.

**Comment by dejj** [comment]
I have improved on the fix. It now handles escaping/unescaping of `#` for anchors.
Created PR https://github.com/linuxmint/xreader/pull/487
